In [86]:
import pandas as pd

In [87]:
pd.__version__

'3.0.3'

In [88]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 72f2fea91530b5abb3cf2100cb22d84e504695c0
python                : 3.12.6
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_India.1252

pandas                : 3.0.3
numpy                 : 2.3.1
dateutil              : 2.9.0.post0
pip                   : 25.2
Cython                : None
sphinx                : None
IPython               : 9.4.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.4
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : 3.10.7
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : 2.0.43
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : 0.24.0
qtpy                  : None
pyqt5                 : None

# Dataframe Basics

In [89]:
import numpy as np
data={
    'fruits':['apple','orange','strawberry','cherry','banana'],
    'color':['red','orange','reddish','pinkish-red','yellowish-white'],
    'price':[200,150,250,120,60]
}

labels=[1,2,3,4,5]

df=pd.DataFrame(data, index=labels)
print(df)

       fruits            color  price
1       apple              red    200
2      orange           orange    150
3  strawberry          reddish    250
4      cherry      pinkish-red    120
5      banana  yellowish-white     60

In [90]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fruits  5 non-null      str
 1   color   5 non-null      str
 2   price   5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 160.0 bytes

In [91]:
df.describe()

            price
count    5.000000
mean   156.000000
std     73.006849
min     60.000000
25%    120.000000
50%    150.000000
75%    200.000000
max    250.000000

In [92]:
df.iloc[:3]

       fruits    color  price
1       apple      red    200
2      orange   orange    150
3  strawberry  reddish    250

In [93]:
df.head()

       fruits            color  price
1       apple              red    200
2      orange           orange    150
3  strawberry          reddish    250
4      cherry      pinkish-red    120
5      banana  yellowish-white     60

In [94]:
df.loc[:,['price','fruits']]

   price      fruits
1    200       apple
2    150      orange
3    250  strawberry
4    120      cherry
5     60      banana

In [95]:
df.loc[df.index[[3,4]],['fruits',"color"]]

   fruits            color
4  cherry      pinkish-red
5  banana  yellowish-white

In [96]:
df[df['price'] >=150]

       fruits    color  price
1       apple      red    200
2      orange   orange    150
3  strawberry  reddish    250

In [97]:
df[df['price'].isnull()]

Empty DataFrame
Columns: [fruits, color, price]
Index: []

In [98]:
df[(df['color']=='red') | (df['price']>=150)]

       fruits    color  price
1       apple      red    200
2      orange   orange    150
3  strawberry  reddish    250

In [99]:
df[df['price'].between(100,222)]

   fruits        color  price
1   apple          red    200
2  orange       orange    150
4  cherry  pinkish-red    120

In [100]:
df.head()

       fruits            color  price
1       apple              red    200
2      orange           orange    150
3  strawberry          reddish    250
4      cherry      pinkish-red    120
5      banana  yellowish-white     60

In [101]:
df.loc[5,'price'] =120
df.loc[4,'price']=180
df

       fruits            color  price
1       apple              red    200
2      orange           orange    150
3  strawberry          reddish    250
4      cherry      pinkish-red    180
5      banana  yellowish-white    120

In [102]:
df['price'].sum()

np.int64(900)

In [103]:
df.groupby('fruits')['price'].mean()

fruits
apple         200.0
banana        120.0
cherry        180.0
orange        150.0
strawberry    250.0
Name: price, dtype: float64

In [104]:
df.loc[6]=["papaya",'yellow',100]
df

       fruits            color  price
1       apple              red    200
2      orange           orange    150
3  strawberry          reddish    250
4      cherry      pinkish-red    180
5      banana  yellowish-white    120
6      papaya           yellow    100

In [105]:
df=df.drop(3)
df

   fruits            color  price
1   apple              red    200
2  orange           orange    150
4  cherry      pinkish-red    180
5  banana  yellowish-white    120
6  papaya           yellow    100

In [106]:
df.loc[7]=['apple', 'red',250]

In [107]:
df

   fruits            color  price
1   apple              red    200
2  orange           orange    150
4  cherry      pinkish-red    180
5  banana  yellowish-white    120
6  papaya           yellow    100
7   apple              red    250

In [108]:
df['fruits'].value_counts()

fruits
apple     2
orange    1
cherry    1
banana    1
papaya    1
Name: count, dtype: int64

In [110]:
df.sort_values(by=['color','price'],ascending=[False,True])
df

   fruits            color  price
1   apple              red    200
2  orange           orange    150
4  cherry      pinkish-red    180
5  banana  yellowish-white    120
6  papaya           yellow    100
7   apple              red    250

In [111]:
df

   fruits            color  price
1   apple              red    200
2  orange           orange    150
4  cherry      pinkish-red    180
5  banana  yellowish-white    120
6  papaya           yellow    100
7   apple              red    250

In [115]:
df.pivot_table(index='fruits',columns='color',values="price", aggfunc='mean')

color   orange  pinkish-red    red  yellow  yellowish-white
fruits
apple      NaN          NaN  225.0     NaN              NaN
banana     NaN          NaN    NaN     NaN            120.0
cherry     NaN        180.0    NaN     NaN              NaN
orange   150.0          NaN    NaN     NaN              NaN
papaya     NaN          NaN    NaN   100.0              NaN